<script lang="ts">
/**
 * Displays the button representing the folder in the MoveItemDialogTargetFolder component.
 *
 * @component MoveItemDialogTargetFolderButton
 * @see MoveItemDialogTargetFolder
 */
export default {
  name: "MoveItemDialogTargetFolderButton",
};
</script>

<script lang="ts" setup>
import { FadeTransition } from "@/components/animations";
import { computed, ref, watchEffect, type Ref, type ComputedRef } from "vue";

const props = defineProps<{
  /**
   * The name of the folder.
   *
   * @type {String}
   * @required
   */
  folderName: string;

  /**
   * The `_id` of the folder.
   *
   * @type {String}
   * @required
   */
  folderId: string;

  /**
   * The `_id` of the folder that is currently selected as the new parent folder.
   *
   * @type {String | null}
   * @required
   */
  selectedNewParentFolderId: string | null;
}>();

/**
 * Whether the folder is selected or not. By default, the folder is selected if the
 * `selectedNewParentFolderId` prop is equal to the folder's `_id`.
 *
 * @type {Ref<Boolean>}
 * @reactive
 */
const isSelected: Ref<boolean> = ref(props.selectedNewParentFolderId === props.folderId);

/**
 * Computed property that generates and returns a dynamic ID for the checkbox input.
 * This is used to associate the checkbox with the label based on the folder's `_id`.
 * This is necessary because the checkbox is hidden and the label is shown instead.
 *
 * The ID is generated by prefixing the folder's `_id` with the string "folder-".
 *
 * @type {ComputedRef<String>}
 * @computed
 */
const checkboxId: ComputedRef<string> = computed(() => {
  return `folder-${props.folderId}`;
});

const emits = defineEmits<{
  /**
   * Emitted when the folder is selected.
   *
   * @event folder-selected
   * @param {String} folderId - The `_id` of the folder that was selected.
   */
  (e: "folder-selected", folderId: string): void;
}>();

/**
 * WatchEffect that updates the `isSelected` ref when the `selectedNewParentFolderId` prop
 * changes. Sets it as true if the `selectedNewParentFolderId` prop is equal to the
 * folder's `_id`. False otherwise.
 *
 * @watch props.selectedNewParentFolderId
 */
watchEffect(() => {
  isSelected.value = props.selectedNewParentFolderId === props.folderId;
});

/**
 * Handles the change event of the checkbox input. Emits the `folder-selected` event
 * with the folder's `_id` (props.folderId) as the payload.
 *
 * @param {Event} event - The change event.
 * @returns {Boolean} - Always returns false.
 * @listens change - The checkbox input's change event.
 * @emits folder-selected
 *
 * @remarks Always returns false to prevent the default behavior of the checkbox input.
 */
function onCheckboxChange(event: Event): boolean {
  event.preventDefault();
  emits("folder-selected", props.folderId);
  return false;
}
</script>

<template>
  <label
    class="move-item__target-list__target__name"
    :for="checkboxId"
    data-test="move-item-target-folder-button"
    >{{ folderName }}
    <FadeTransition>
      <input
        v-show="isSelected"
        :id="checkboxId"
        :checked="isSelected"
        @change="onCheckboxChange"
        type="checkbox"
        class="move-item__target-list__target__checkbox"
        data-test="move-item-target-folder-selected-icon"
      />
    </FadeTransition>
  </label>
</template>

<style lang="scss" scoped>
.move-item__target-list__target {
  &__name {
    display: flex;
    align-items: center;
    justify-content: space-between;
    cursor: pointer;
  }
  &__checkbox {
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    border-radius: 3px;
    height: 1em;
    width: 1em;
    align-self: center;
    transition: all 0.25s ease-in-out;
    cursor: pointer;
    &:checked {
      background: url("@/assets/icons/checked-icon-black.svg") no-repeat center center / cover;
    }
  }
}
</style>
